In [78]:
import tensorflow as tf
import numpy as np
import random
import keras
from sklearn.preprocessing import OneHotEncoder

In [79]:
#Ensures same random number are generated during each run
tf.random.set_seed(42)
random.seed(0)
np.random.seed(0)

In [80]:
temp = []
for i in range(128):
    b = bin(i)
    b = b[2:]
    l = len(b)
    if l<7:
        b = '0'*(7-l) + b
    b = list(b)
    b = list(map(int, b))
    temp.append(b)

In [81]:
b = bin(10)
print(b, type(b))

def alph_to_bin(al):
    ch = bin(al)[2:]
    ch = list(ch)
    ch = list(map(int, ch))
    return ch

alph_to_bin(ord('a'))

0b1010 <class 'str'>


[1, 1, 0, 0, 0, 0, 1]

In [82]:
for i in range(ord('a'), ord('z') + 1):
    print(chr(i), alph_to_bin(i))

a [1, 1, 0, 0, 0, 0, 1]
b [1, 1, 0, 0, 0, 1, 0]
c [1, 1, 0, 0, 0, 1, 1]
d [1, 1, 0, 0, 1, 0, 0]
e [1, 1, 0, 0, 1, 0, 1]
f [1, 1, 0, 0, 1, 1, 0]
g [1, 1, 0, 0, 1, 1, 1]
h [1, 1, 0, 1, 0, 0, 0]
i [1, 1, 0, 1, 0, 0, 1]
j [1, 1, 0, 1, 0, 1, 0]
k [1, 1, 0, 1, 0, 1, 1]
l [1, 1, 0, 1, 1, 0, 0]
m [1, 1, 0, 1, 1, 0, 1]
n [1, 1, 0, 1, 1, 1, 0]
o [1, 1, 0, 1, 1, 1, 1]
p [1, 1, 1, 0, 0, 0, 0]
q [1, 1, 1, 0, 0, 0, 1]
r [1, 1, 1, 0, 0, 1, 0]
s [1, 1, 1, 0, 0, 1, 1]
t [1, 1, 1, 0, 1, 0, 0]
u [1, 1, 1, 0, 1, 0, 1]
v [1, 1, 1, 0, 1, 1, 0]
w [1, 1, 1, 0, 1, 1, 1]
x [1, 1, 1, 1, 0, 0, 0]
y [1, 1, 1, 1, 0, 0, 1]
z [1, 1, 1, 1, 0, 1, 0]


In [83]:
input_shape = (7,)

model = tf.keras.Sequential()

model.add(tf.keras.layers.Dense(16, input_shape=input_shape, activation='relu' ))
model.add(tf.keras.layers.Dense(7, activation='linear'))
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_23 (Dense)            (None, 16)                128       
                                                                 
 dense_24 (Dense)            (None, 7)                 119       
                                                                 
Total params: 247
Trainable params: 247
Non-trainable params: 0
_________________________________________________________________


In [84]:
# model.predict(tf.constant(alph_to_bin(ord('a'))))
# tf.constant(alph_to_bin(ord('a')))
input_tensor = tf.convert_to_tensor(alph_to_bin(ord('a')), dtype=tf.float32)
input_tensor = tf.reshape(input_tensor, (7,))
model.predict(tf.expand_dims(input_tensor, axis=0))

1/1 [==============================] - 0s 70ms/step


array([[-0.93460834,  0.04893687,  0.05621722,  0.7036843 ,  0.14198218,
        -0.3780187 , -0.6234064 ]], dtype=float32)

In [85]:
ans = model.predict(tf.expand_dims(input_tensor, axis=0))
ans.reshape((7,))
ans.shape

1/1 [==============================] - 0s 27ms/step


(1, 7)

In [86]:
input_tensor = tf.convert_to_tensor(alph_to_bin(ord('a')), dtype=tf.float32)
input_tensor = tf.reshape(input_tensor, (7,))
ans1 = model.predict(tf.expand_dims(input_tensor, axis=0))

result = tf.concat([ans, ans1], axis=0) 
print(result)

1/1 [==============================] - 0s 21ms/step
tf.Tensor(
[[-0.93460834  0.04893687  0.05621722  0.7036843   0.14198218 -0.3780187
  -0.6234064 ]
 [-0.93460834  0.04893687  0.05621722  0.7036843   0.14198218 -0.3780187
  -0.6234064 ]], shape=(2, 7), dtype=float32)


In [87]:
labels = []
for i in range(0, 128):
    labels.append(i)
print(labels)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127]


In [88]:
results = ans

for i in range(127):
    input_tensor = tf.convert_to_tensor(temp[i], dtype=tf.float32)
    input_tensor = tf.reshape(input_tensor, (7,))
    ans1 = model.predict(tf.expand_dims(input_tensor, axis=0))
    results = tf.concat([results, ans1], axis=0)
print(results)

1/1 [==============================] - 0s 18ms/step
tf.Tensor(
[[-9.34608340e-01  4.89368662e-02  5.62172160e-02  7.03684270e-01
   1.41982183e-01 -3.78018707e-01 -6.23406410e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-3.77634406e-01  6.83094487e-02 -5.44994324e-02  1.92454979e-01
   1.31965298e-02 -3.03248972e-01 -3.20654899e-01]
 [-2.44740993e-01 -8.24758336e-02 -2.17540175e-01  3.00378293e-01
  -1.10217720e-01  2.32385360e-02 -1.31277919e-01]
 [-3.28042537e-01 -1.94496557e-01 -9.14824232e-02  8.71671960e-02
  -2.19959453e-01 -1.02383025e-01 -3.05328697e-01]
 [-3.34559143e-01  3.26219916e-01 -1.84187621e-01  4.98221815e-02
   3.95029858e-02 -2.42397264e-01 -2.75268883e-01]
 [-7.70167112e-01  3.43681812e-01 -7.27210417e-02  2.98694044e-01
   7.03377724e-02 -4.79075283e-01 -5.64516366e-01]
 [-3.16213578e-01 -3.22812796e-02 -2.33687460e-01  9.51719210e-02
  -6.33429587e-02 -8.35267976e-02 -1.39210701e-01]
 

In [89]:
# results = ans

# for i in range(ord('a') + 1, ord('z') + 1):
#     input_tensor = tf.convert_to_tensor(alph_to_bin(i), dtype=tf.float32)
#     input_tensor = tf.reshape(input_tensor, (7,))
#     ans1 = model.predict(tf.expand_dims(input_tensor, axis=0))
#     results = tf.concat([results, ans1], axis=0)
# print(results)

In [90]:
results.shape

TensorShape([128, 7])

In [91]:
#Demo encryption
plain_text = 'hello'
for i in plain_text:
    input_tensor = tf.convert_to_tensor(alph_to_bin(ord(i)), dtype=tf.float32)
    input_tensor = tf.reshape(input_tensor, (7,))
    ans1 = model.predict(tf.expand_dims(input_tensor, axis=0))
    print(ans1)

1/1 [==============================] - 0s 21ms/step
[[-0.91132545  0.4115393  -0.0933212   0.35852143 -0.26180315 -0.17483059
  -0.9276288 ]]
1/1 [==============================] - 0s 18ms/step
[[-1.2804384   0.34833118  0.01027439  0.75798756  0.22317053 -0.5387827
  -0.90801895]]
1/1 [==============================] - 0s 17ms/step
[[-1.1774939   0.75919455 -0.31590098  0.34534633 -0.1815464  -0.37575123
  -1.2159768 ]]
1/1 [==============================] - 0s 18ms/step
[[-1.1774939   0.75919455 -0.31590098  0.34534633 -0.1815464  -0.37575123
  -1.2159768 ]]
1/1 [==============================] - 0s 19ms/step
[[-1.4131734   0.4693577  -0.27267766  0.46681422 -0.23441108 -0.3990432
  -1.4014207 ]]


In [92]:
#Defining model architecture
model_dec = keras.Sequential([
    keras.layers.Dense(128, activation='relu', input_shape=(7,)),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    # keras.layers.Dense(256, activation='relu'),
    keras.layers.Dense(128, activation='softmax')
])
model_dec.summary()


Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_25 (Dense)            (None, 128)               1024      
                                                                 
 dense_26 (Dense)            (None, 64)                8256      
                                                                 
 dense_27 (Dense)            (None, 128)               8320      
                                                                 
 dense_28 (Dense)            (None, 128)               16512     
                                                                 
Total params: 34,112
Trainable params: 34,112
Non-trainable params: 0
_________________________________________________________________


In [93]:
#Created to stop training when accuracy hits 100%
class CustomCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        if logs.get('accuracy') >= 1:
            self.model.stop_training = True


In [94]:
# optimizer = keras.optimizers.Adam(lr=0.0001)
callback = CustomCallback()
model_dec.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [95]:
results.shape

TensorShape([128, 7])

In [96]:
#Creating the labels
labels = []
for i in range(128):
    l = [0] * 128
    l[i] = 1
    labels.append(l)
print(labels)
labels = tf.convert_to_tensor(labels)
labels.shape

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

TensorShape([128, 128])

In [97]:
#Training the decryption modsel
epochs = 1000
model_dec.fit(results, labels, epochs=epochs, callbacks=[callback])

Epoch 1/1000


4/4 [==============================] - 1s 4ms/step - loss: 4.8573 - accuracy: 0.0000e+00
Epoch 2/1000
4/4 [==============================] - 0s 4ms/step - loss: 4.8438 - accuracy: 0.0078
Epoch 3/1000
4/4 [==============================] - 0s 3ms/step - loss: 4.8359 - accuracy: 0.0078
Epoch 4/1000
4/4 [==============================] - 0s 4ms/step - loss: 4.8275 - accuracy: 0.0078
Epoch 5/1000
4/4 [==============================] - 0s 4ms/step - loss: 4.8176 - accuracy: 0.0078
Epoch 6/1000
4/4 [==============================] - 0s 3ms/step - loss: 4.8061 - accuracy: 0.0156
Epoch 7/1000
4/4 [==============================] - 0s 4ms/step - loss: 4.7926 - accuracy: 0.0156
Epoch 8/1000
4/4 [==============================] - 0s 3ms/step - loss: 4.7755 - accuracy: 0.0156
Epoch 9/1000
4/4 [==============================] - 0s 3ms/step - loss: 4.7530 - accuracy: 0.0312
Epoch 10/1000
4/4 [==============================] - 0s 3ms/step - loss: 4.7258 - accuracy: 0.0391
Epoch 11/1000
4/4 [=========

In [98]:
#Saving the decryption model
model_dec.save('dec_model.keras')