In [68]:
import tensorflow as tf
import numpy as np
import random
import keras
from sklearn.preprocessing import OneHotEncoder

In [69]:
#Ensures same random number are generated during each run
tf.random.set_seed(42)
random.seed(0)
np.random.seed(0)

In [70]:
b = bin(10)
print(b, type(b))

def alph_to_bin(al):
    ch = bin(al)[2:]
    ch = list(ch)
    ch = list(map(int, ch))
    return ch

alph_to_bin(ord('a'))

0b1010 <class 'str'>


[1, 1, 0, 0, 0, 0, 1]

In [71]:
for i in range(ord('a'), ord('z') + 1):
    print(chr(i), alph_to_bin(i))

a [1, 1, 0, 0, 0, 0, 1]
b [1, 1, 0, 0, 0, 1, 0]
c [1, 1, 0, 0, 0, 1, 1]
d [1, 1, 0, 0, 1, 0, 0]
e [1, 1, 0, 0, 1, 0, 1]
f [1, 1, 0, 0, 1, 1, 0]
g [1, 1, 0, 0, 1, 1, 1]
h [1, 1, 0, 1, 0, 0, 0]
i [1, 1, 0, 1, 0, 0, 1]
j [1, 1, 0, 1, 0, 1, 0]
k [1, 1, 0, 1, 0, 1, 1]
l [1, 1, 0, 1, 1, 0, 0]
m [1, 1, 0, 1, 1, 0, 1]
n [1, 1, 0, 1, 1, 1, 0]
o [1, 1, 0, 1, 1, 1, 1]
p [1, 1, 1, 0, 0, 0, 0]
q [1, 1, 1, 0, 0, 0, 1]
r [1, 1, 1, 0, 0, 1, 0]
s [1, 1, 1, 0, 0, 1, 1]
t [1, 1, 1, 0, 1, 0, 0]
u [1, 1, 1, 0, 1, 0, 1]
v [1, 1, 1, 0, 1, 1, 0]
w [1, 1, 1, 0, 1, 1, 1]
x [1, 1, 1, 1, 0, 0, 0]
y [1, 1, 1, 1, 0, 0, 1]
z [1, 1, 1, 1, 0, 1, 0]


In [72]:
input_shape = (7,)

model = tf.keras.Sequential()

model.add(tf.keras.layers.Dense(16, input_shape=input_shape, activation='relu' ))
model.add(tf.keras.layers.Dense(7, activation='linear'))
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_20 (Dense)            (None, 16)                128       
                                                                 
 dense_21 (Dense)            (None, 7)                 119       
                                                                 
Total params: 247
Trainable params: 247
Non-trainable params: 0
_________________________________________________________________


In [73]:
# model.predict(tf.constant(alph_to_bin(ord('a'))))
# tf.constant(alph_to_bin(ord('a')))
input_tensor = tf.convert_to_tensor(alph_to_bin(ord('a')), dtype=tf.float32)
input_tensor = tf.reshape(input_tensor, (7,))
model.predict(tf.expand_dims(input_tensor, axis=0))

1/1 [==============================] - 0s 140ms/step


array([[-0.93460834,  0.04893687,  0.05621722,  0.7036843 ,  0.14198218,
        -0.3780187 , -0.6234064 ]], dtype=float32)

In [74]:
ans = model.predict(tf.expand_dims(input_tensor, axis=0))
ans.reshape((7,))
ans.shape

1/1 [==============================] - 0s 83ms/step


(1, 7)

In [75]:
input_tensor = tf.convert_to_tensor(alph_to_bin(ord('a')), dtype=tf.float32)
input_tensor = tf.reshape(input_tensor, (7,))
ans1 = model.predict(tf.expand_dims(input_tensor, axis=0))

result = tf.concat([ans, ans1], axis=0) 
print(result)

1/1 [==============================] - 0s 57ms/step


tf.Tensor(
[[-0.93460834  0.04893687  0.05621722  0.7036843   0.14198218 -0.3780187
  -0.6234064 ]
 [-0.93460834  0.04893687  0.05621722  0.7036843   0.14198218 -0.3780187
  -0.6234064 ]], shape=(2, 7), dtype=float32)


In [76]:
labels = []
for i in range(0, 26):
    labels.append(i)
print(labels)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


In [77]:
results = ans

for i in range(ord('a') + 1, ord('z') + 1):
    input_tensor = tf.convert_to_tensor(alph_to_bin(i), dtype=tf.float32)
    input_tensor = tf.reshape(input_tensor, (7,))
    ans1 = model.predict(tf.expand_dims(input_tensor, axis=0))
    results = tf.concat([results, ans1], axis=0)
print(results)

1/1 [==============================] - 0s 36ms/step
tf.Tensor(
[[-9.34608340e-01  4.89368662e-02  5.62172160e-02  7.03684270e-01
   1.41982183e-01 -3.78018707e-01 -6.23406410e-01]
 [-5.47664583e-01 -2.84132391e-01 -1.91055357e-01  6.19478822e-01
  -5.63344499e-03 -1.38237346e-02 -2.70154715e-01]
 [-7.94743121e-01 -2.71576792e-01 -5.39941490e-02  5.18564343e-01
  -6.36454299e-02 -1.71987548e-01 -5.76053143e-01]
 [-8.44605267e-01  1.93688199e-01 -4.93631773e-02  5.52234769e-01
   2.71381348e-01 -3.63302350e-01 -6.22031152e-01]
 [-1.28043842e+00  3.48331183e-01  1.02743907e-02  7.57987559e-01
   2.23170534e-01 -5.38782716e-01 -9.08018947e-01]
 [-7.87271261e-01 -1.41283467e-01 -1.22114308e-01  5.48061073e-01
   1.02959126e-01 -6.27087057e-02 -4.33479875e-01]
 [-1.15771663e+00 -3.13344039e-02 -8.29120353e-02  6.66200340e-01
   3.00753657e-02 -3.26899439e-01 -8.01186442e-01]
 [-9.11325455e-01  4.11539286e-01 -9.33212042e-02  3.58521432e-01
  -2.61803150e-01 -1.74830586e-01 -9.27628815e-01]
 

In [78]:
results.shape

TensorShape([26, 7])

In [79]:
model_dec = keras.Sequential([
    keras.layers.Dense(128, activation='relu', input_shape=(7,)),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(26, activation='softmax')
])
model_dec.summary()


Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_22 (Dense)            (None, 128)               1024      
                                                                 
 dense_23 (Dense)            (None, 64)                8256      
                                                                 
 dense_24 (Dense)            (None, 26)                1690      
                                                                 
Total params: 10,970
Trainable params: 10,970
Non-trainable params: 0
_________________________________________________________________


In [80]:
model_dec.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [81]:
results.shape

TensorShape([26, 7])

In [82]:
# enc = OneHotEncoder(handle_unknown='ignore')
# labels = enc.fit([labels])
labels = []
for i in range(26):
    l = [0] * 26
    l[i] = 1
    labels.append(l)
print(labels)
labels = tf.convert_to_tensor(labels)
labels.shape

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

TensorShape([26, 26])

In [83]:
epochs = 1000

model_dec.fit(results, labels, epochs=epochs)

Epoch 1/1000


1/1 [==============================] - 1s 1s/step - loss: 3.2700 - accuracy: 0.0000e+00
Epoch 2/1000
1/1 [==============================] - 0s 15ms/step - loss: 3.2624 - accuracy: 0.0000e+00
Epoch 3/1000
1/1 [==============================] - 0s 12ms/step - loss: 3.2548 - accuracy: 0.0385
Epoch 4/1000
1/1 [==============================] - 0s 11ms/step - loss: 3.2480 - accuracy: 0.0385
Epoch 5/1000
1/1 [==============================] - 0s 12ms/step - loss: 3.2416 - accuracy: 0.0385
Epoch 6/1000
1/1 [==============================] - 0s 11ms/step - loss: 3.2352 - accuracy: 0.0385
Epoch 7/1000
1/1 [==============================] - 0s 15ms/step - loss: 3.2293 - accuracy: 0.0385
Epoch 8/1000
1/1 [==============================] - 0s 12ms/step - loss: 3.2234 - accuracy: 0.0769
Epoch 9/1000
1/1 [==============================] - 0s 14ms/step - loss: 3.2178 - accuracy: 0.0769
Epoch 10/1000
1/1 [==============================] - 0s 11ms/step - loss: 3.2125 - accuracy: 0.0385
Epoch 11/1000
1/